using Microsoft.EntityFrameworkCore;
using StreetBiz.Application.Common.Exceptions;
using StreetBiz.Application.Common.Interfaces;
using StreetBiz.Application.Common.Models;
using StreetBiz.Application.Common.Security;
using StreetBiz.Infrastructure.Persistence.ScaffoldedModels;

namespace StreetBiz.Infrastructure.Persistence.Repositories;

public sealed class BusinessRegistrationRepository(
    StreetBizDbContext dbContext,
    IDateTimeProvider clock) : IBusinessRegistrationRepository
{
    public Task<bool> HasActivePendingAsync(long vendorId, CancellationToken cancellationToken, long? excludeRegistrationId = null) =>
        dbContext.BusinessRegistrations.AsNoTracking()
            .AnyAsync(r => r.vendor_id == vendorId
                        && r.registration_id != excludeRegistrationId
                        && (r.registration_status == RegistrationStatuses.Submitted
                         || r.registration_status == RegistrationStatuses.UnderReview),
                      cancellationToken);

    public async Task<long> CreateAsync(long vendorId, NewBizRegistration data, CancellationToken cancellationToken)
    {
        var entity = new BusinessRegistration
        {
            vendor_id = vendorId,
            vendor_type = data.VendorType,
            display_name = data.DisplayName,
            declared_address = data.DeclaredAddress,
            address_latitude = data.AddressLatitude,
            address_longitude = data.AddressLongitude,
            ward_unit_id = data.WardUnitId,
            registration_status = RegistrationStatuses.Submitted,
            fast_track_flag = false,
            // ward_unit_type and reviewer_role are computed columns — never set here.
            // created_at is generated by the database default.
        };

        dbContext.BusinessRegistrations.Add(entity);
        await dbContext.SaveChangesAsync(cancellationToken);
        return entity.registration_id;
    }

    public async Task<BizRegistration?> GetByIdAsync(long registrationId, CancellationToken cancellationToken)
    {
        var e = await dbContext.BusinessRegistrations.AsNoTracking()
            .FirstOrDefaultAsync(r => r.registration_id == registrationId, cancellationToken);
        return e is null ? null : Map(e);
    }

    public async Task<IReadOnlyList<BizRegistration>> ListByVendorAsync(long vendorId, CancellationToken cancellationToken)
    {
        var list = await dbContext.BusinessRegistrations.AsNoTracking()
            .Where(r => r.vendor_id == vendorId)
            .OrderByDescending(r => r.created_at)
            .ToListAsync(cancellationToken);
        return list.Select(Map).ToList();
    }

    public async Task UpdateAndResubmitAsync(long registrationId, NewBizRegistration data, CancellationToken cancellationToken)
    {
        var e = await dbContext.BusinessRegistrations
            .FirstOrDefaultAsync(r => r.registration_id == registrationId, cancellationToken)
            ?? throw new NotFoundException(RegMessages.NotFound);

        e.vendor_type = data.VendorType;
        e.display_name = data.DisplayName;
        e.declared_address = data.DeclaredAddress;
        e.address_latitude = data.AddressLatitude;
        e.address_longitude = data.AddressLongitude;
        e.ward_unit_id = data.WardUnitId;
        e.registration_status = RegistrationStatuses.Submitted;
        e.updated_at = clock.UtcNow;
        await dbContext.SaveChangesAsync(cancellationToken);
        // Switching to itinerant drops the licence requirement, so the flag is recomputed.
        await RefreshFastTrackAsync(registrationId, cancellationToken);
    }

    public async Task SetStatusAsync(long registrationId, string status, CancellationToken cancellationToken)
    {
        var e = await dbContext.BusinessRegistrations
            .FirstOrDefaultAsync(r => r.registration_id == registrationId, cancellationToken);
        if (e is null)
        {
            return;
        }

        e.registration_status = status;
        e.updated_at = clock.UtcNow;
        await dbContext.SaveChangesAsync(cancellationToken);
    }

    public async Task<long> AddEvidenceAsync(long registrationId, NewRegistrationEvidence evidence, CancellationToken cancellationToken)
    {
        var entity = new RegistrationEvidence
        {
            registration_id = registrationId,
            evidence_type = evidence.EvidenceType,
            file_url = evidence.FileUrl,
            ocr_extracted_data = evidence.OcrExtractedData,
            // BR-47 / PRI-06: identity documents carry an explicit disposal date.
            retention_expires_at = clock.UtcNow.Add(EvidenceFiles.RetentionPeriod),
            // uploaded_at is generated by the database default.
        };

        dbContext.RegistrationEvidences.Add(entity);
        await dbContext.SaveChangesAsync(cancellationToken);
        await RefreshFastTrackAsync(registrationId, cancellationToken);
        return entity.evidence_id;
    }

    /// <summary>
    /// REG-06: a fixed storefront that supplied a cross-checkable business licence is
    /// flagged for expedited handling. The flag only orders the ward queue — the officer
    /// still makes an explicit decision.
    /// </summary>
    private async Task RefreshFastTrackAsync(long registrationId, CancellationToken cancellationToken)
    {
        var entity = await dbContext.BusinessRegistrations
            .FirstOrDefaultAsync(r => r.registration_id == registrationId, cancellationToken);
        if (entity is null)
        {
            return;
        }

        var fastTrack = entity.vendor_type == VendorTypes.FixedStorefront
            && await dbContext.RegistrationEvidences.AsNoTracking().AnyAsync(
                e => e.registration_id == registrationId
                     && e.evidence_type == EvidenceTypes.BusinessLicense,
                cancellationToken);

        if (entity.fast_track_flag == fastTrack)
        {
            return;
        }

        entity.fast_track_flag = fastTrack;
        await dbContext.SaveChangesAsync(cancellationToken);
    }

    public async Task<IReadOnlyList<BizRegistrationEvidence>> ListEvidenceAsync(long registrationId, CancellationToken cancellationToken) =>
        await dbContext.RegistrationEvidences.AsNoTracking()
            .Where(e => e.registration_id == registrationId)
            .OrderBy(e => e.uploaded_at)
            .Select(e => new BizRegistrationEvidence(e.evidence_id, e.registration_id, e.evidence_type, e.file_url, e.uploaded_at))
            .ToListAsync(cancellationToken);

    public Task<bool> HasActiveContractAsync(long registrationId, CancellationToken cancellationToken) =>
        (from c in dbContext.RentalContracts.AsNoTracking()
         join a in dbContext.RentalApplications.AsNoTracking()
             on c.application_id equals a.application_id
         where a.registration_id == registrationId && c.contract_status == "ACTIVE"
         select c.contract_id)
        .AnyAsync(cancellationToken);

    public Task<bool> EvidenceBelongsToWardAsync(
        long ownerUserId,
        string fileUrl,
        int wardUnitId,
        CancellationToken cancellationToken) =>
        dbContext.RegistrationEvidences.AsNoTracking()
            .AnyAsync(e => e.file_url == fileUrl
                        && e.registration.ward_unit_id == wardUnitId
                        && e.registration.vendor.user_id == ownerUserId,
                      cancellationToken);

    public Task<bool> HasApprovedRegistrationAsync(long vendorId, CancellationToken cancellationToken) =>
        dbContext.BusinessRegistrations.AsNoTracking()
            .AnyAsync(r => r.vendor_id == vendorId && r.registration_status == RegistrationStatuses.Approved, cancellationToken);

    private static BizRegistration Map(BusinessRegistration r) => new(
        r.registration_id, r.vendor_id, r.vendor_type, r.display_name, r.declared_address,
        r.address_latitude, r.address_longitude, r.ward_unit_id, r.registration_status,
        r.fast_track_flag, r.review_decision_reason, r.reviewed_at, r.created_at, r.updated_at);
}
