using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using StreetBiz.Application.Common.Exceptions;
using StreetBiz.Application.Common.Interfaces;
using StreetBiz.Application.Common.Models;
using StreetBiz.Application.Common.Security;
using StreetBiz.Infrastructure.Persistence.ScaffoldedModels;

namespace StreetBiz.Infrastructure.Persistence.Repositories;

public sealed class UserAccountRepository(
    StreetBizDbContext dbContext,
    IDateTimeProvider clock) : IUserAccountRepository
{
    public Task<bool> PhoneExistsAsync(string phoneNumber, CancellationToken cancellationToken) =>
        dbContext.UserAccounts.AsNoTracking()
            .AnyAsync(u => u.phone_number == phoneNumber, cancellationToken);

    public async Task<AppUser?> GetByPhoneAsync(string phoneNumber, CancellationToken cancellationToken)
    {
        var entity = await dbContext.UserAccounts.AsNoTracking()
            .FirstOrDefaultAsync(u => u.phone_number == phoneNumber, cancellationToken);
        return entity is null ? null : Map(entity);
    }

    public async Task<AppUser?> GetByIdAsync(long userId, CancellationToken cancellationToken)
    {
        var entity = await dbContext.UserAccounts.AsNoTracking()
            .FirstOrDefaultAsync(u => u.user_id == userId, cancellationToken);
        return entity is null ? null : Map(entity);
    }

    public async Task<long> CreateAsync(NewUser user, CancellationToken cancellationToken)
    {
        var entity = new UserAccount
        {
            phone_number = user.PhoneNumber,
            password_hash = user.PasswordHash,
            full_name = user.FullName,
            role_code = user.RoleCode,
            ward_unit_id = user.WardUnitId,
            account_status = user.AccountStatus,
            phone_verified_at = user.PhoneVerifiedAtUtc,
            // created_at is generated by the database default (sysutcdatetime()).
        };

        dbContext.UserAccounts.Add(entity);

        try
        {
            await dbContext.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateException ex) when (IsUniquePhoneViolation(ex))
        {
            // PhoneExistsAsync is checked earlier, but two concurrent registrations for the
            // same number (e.g. a doubly-submitted form) can both pass that check before either
            // inserts; the UQ index on phone_number is the real guard. Surface it as a normal
            // conflict rather than letting the raw SqlException reach the client as a 500.
            throw new ConflictException(AppMessages.PhoneAlreadyRegistered);
        }

        // Create the linked Vendor row for vendor accounts.
        if (user.RoleCode == RoleCodes.Vendor)
        {
            dbContext.Vendors.Add(new Vendor
            {
                user_id = entity.user_id,
                created_at = clock.UtcNow,
            });
            await dbContext.SaveChangesAsync(cancellationToken);
        }

        return entity.user_id;
    }

    public async Task UpdatePasswordHashAsync(long userId, string passwordHash, CancellationToken cancellationToken)
    {
        var entity = await dbContext.UserAccounts
            .FirstOrDefaultAsync(u => u.user_id == userId, cancellationToken);
        if (entity is null)
        {
            return;
        }

        entity.password_hash = passwordHash;
        entity.updated_at = clock.UtcNow;
        await dbContext.SaveChangesAsync(cancellationToken);
    }

    // SQL Server error 2601 = duplicate key on a unique index, 2627 = on a unique constraint.
    private static bool IsUniquePhoneViolation(DbUpdateException ex) =>
        ex.InnerException is SqlException { Number: 2601 or 2627 };

    private static AppUser Map(UserAccount u) => new(
        u.user_id, u.phone_number, u.password_hash, u.full_name, u.role_code,
        u.ward_unit_id, u.account_status, u.phone_verified_at);
}
