using Microsoft.EntityFrameworkCore;
using StreetBiz.Application.Common.Interfaces;
using StreetBiz.Application.Common.Models;
using StreetBiz.Application.Common.Security;
using StreetBiz.Infrastructure.Persistence.ScaffoldedModels;

namespace StreetBiz.Infrastructure.Persistence.Repositories;

public sealed class UserAccountRepository(
    StreetBizDbContext dbContext,
    IDateTimeProvider clock) : IUserAccountRepository
{
    public Task<bool> PhoneExistsAsync(string phoneNumber, CancellationToken cancellationToken) =>
        dbContext.UserAccounts.AsNoTracking()
            .AnyAsync(u => u.phone_number == phoneNumber, cancellationToken);

    public async Task<AppUser?> GetByPhoneAsync(string phoneNumber, CancellationToken cancellationToken)
    {
        var entity = await dbContext.UserAccounts.AsNoTracking()
            .FirstOrDefaultAsync(u => u.phone_number == phoneNumber, cancellationToken);
        return entity is null ? null : Map(entity);
    }

    public async Task<AppUser?> GetByIdAsync(long userId, CancellationToken cancellationToken)
    {
        var entity = await dbContext.UserAccounts.AsNoTracking()
            .FirstOrDefaultAsync(u => u.user_id == userId, cancellationToken);
        return entity is null ? null : Map(entity);
    }

    public async Task<long> CreateAsync(NewUser user, CancellationToken cancellationToken)
    {
        var entity = new UserAccount
        {
            phone_number = user.PhoneNumber,
            password_hash = user.PasswordHash,
            full_name = user.FullName,
            role_code = user.RoleCode,
            ward_unit_id = user.WardUnitId,
            account_status = user.AccountStatus,
            phone_verified_at = user.PhoneVerifiedAtUtc,
            // created_at is generated by the database default (sysutcdatetime()).
        };

        dbContext.UserAccounts.Add(entity);
        await dbContext.SaveChangesAsync(cancellationToken);

        // Create the linked Vendor row for vendor accounts.
        if (user.RoleCode == RoleCodes.Vendor)
        {
            dbContext.Vendors.Add(new Vendor
            {
                user_id = entity.user_id,
                created_at = clock.UtcNow,
            });
            await dbContext.SaveChangesAsync(cancellationToken);
        }

        return entity.user_id;
    }

    public async Task UpdatePasswordHashAsync(long userId, string passwordHash, CancellationToken cancellationToken)
    {
        var entity = await dbContext.UserAccounts
            .FirstOrDefaultAsync(u => u.user_id == userId, cancellationToken);
        if (entity is null)
        {
            return;
        }

        entity.password_hash = passwordHash;
        entity.updated_at = clock.UtcNow;
        await dbContext.SaveChangesAsync(cancellationToken);
    }

    private static AppUser Map(UserAccount u) => new(
        u.user_id, u.phone_number, u.password_hash, u.full_name, u.role_code,
        u.ward_unit_id, u.account_status, u.phone_verified_at);
}
